spring.application.name=backend
server.port=8081

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5435/angeldb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA DDL Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
