spring.application.name=backend
server.port=8081

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5435/angeldb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA DDL Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Max Payload & Multipart Upload Size (Allow Base64 image data)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.max-http-form-post-size=50MB
